name: GitHub Pages
on:
  push:
    branches:
      - master
  pull_request:
defaults:
  run:
    working-directory: ./site
jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
          cache+: 'npm'
      - name: install modules
        run: npm install
      - name: build gatsby
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
